[package]
name = "tinted-builder-rust"
version = "0.21.0"
edition = "2021"
authors = ["Jamy Golden <code@jamygolden.com>", "Tinted Theming <tintedtheming@proton.me>"]
license = "GPL-3.0-only"
description = "Simple Base16, Base24 and Tinted8 compliant rendering of mustache templates"
keywords = ["base16", "tinted8", "mustache", "template"]
categories = ["template-engine"]
homepage = "https://github.com/tinted-theming/tinted-builder-rust"
repository = "https://github.com/tinted-theming/tinted-builder-rust"
documentation = "https://github.com/tinted-theming/tinted-builder-rust"
readme = "README.md"
rust-version.workspace = true

[dependencies]
anyhow = "1.0.103"
clap = "4.5.51"
dirs.workspace = true
regex.workspace = true
ribboncurls.workspace = true
semver.workspace = true
serde.workspace = true
serde_yaml.workspace = true
tinted-builder = { path = "../tinted-builder", version = "0.16.0" }
wax = "0.7.0"
which = "8.0.0"

[dev-dependencies]
strip-ansi-escapes.workspace = true

[[bin]]
name = "tinted-builder-rust"
path = "src/main.rs"

[lints]
workspace = true
