[package]
name = "tinted-builder"
description = "A Tinted Theming template builder which uses yaml color schemes to generate theme files."
version = "0.16.0"
edition = "2021"
license = "GPL-3.0-only"
readme = "README.md"
authors = ["Jamy Golden <code@jamygolden.com>", "Tinted Theming <tintedtheming@proton.me>"]
homepage = "https://github.com/tinted-theming/tinted-builder-rust"
repository = "https://github.com/tinted-theming/tinted-builder-rust"
keywords = ["cli", "base16", "base24", "tinted-theming"]
categories = ["command-line-utilities", "template-engine"]
rust-version.workspace = true

[dependencies]
dirs.workspace = true
palette = "0.7.6"
quick-xml = { version = "0.41.0", features = ["serialize"] }
regex.workspace = true
ribboncurls.workspace = true
semver.workspace = true
serde.workspace = true
serde_yaml.workspace = true
thiserror = "2.0.17"
unicode-normalization = "0.1.25"

[build-dependencies]
serde = { workspace = true, features = ["derive"] }
serde_yaml.workspace = true

[dev-dependencies]
anyhow = "1.0.103"
strip-ansi-escapes.workspace = true

[lints]
workspace = true
